"""add unit price column oreder product

Revision ID: 9ff3eb921a82
Revises: 72765cf202b4
Create Date: 2024-04-17 16:04:29.811862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff3eb921a82'
down_revision: Union[str, None] = '72765cf202b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product', sa.Column('unit_price', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product', 'unit_price')
    # ### end Alembic commands ###
