"""add count column oreder product

Revision ID: 72765cf202b4
Revises: 6ef47eb4fa42
Create Date: 2024-04-17 15:49:22.578290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72765cf202b4'
down_revision: Union[str, None] = '6ef47eb4fa42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product', sa.Column('count', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product', 'count')
    # ### end Alembic commands ###
